name: Publish NPM Release
on:
  workflow_run:
    workflows: ["GitHub Release"]
    types: [completed]
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.x"

      - name: ğŸ“¥ Install Dependencies
        run: npm i
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: ğŸ“¥ Install Dependencies
        run: npm i

      - name: Publish NPM Release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}